# Generated by Django 4.0.5 on 2022-06-19 17:55

import Eventos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eventos', '0002_alter_evento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='imagen',
            field=models.ImageField(blank=True, default='eventos/default.jpg', upload_to=Eventos.models.save_image_event),
        ),
    ]
