# Generated by Django 4.0.5 on 2022-06-19 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_producto_options_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='recomendar',
            field=models.BooleanField(default=False),
        ),
    ]
