# Generated by Django 4.0.5 on 2022-06-19 17:05

import Productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='number_prd',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=Productos.models.save_image_category),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=Productos.models.save_image_product),
        ),
    ]
