# Generated by Django 4.0.5 on 2022-06-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ManyToManyField(blank=True, related_name='producto_compra', to='Productos.producto'),
        ),
    ]
