# Generated by Django 4.0.5 on 2022-06-20 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_remove_compra_producto_compra_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto'),
        ),
    ]
